<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PersonaSeeder extends Seeder
{
    public function run(): void
    {
        $personas = [
            [
                'id'               => 1,
                'dni'              => '0603196500506',
                'primer_nombre'    => 'Vicente',
                'segundo_nombre'   => null,
                'primer_apellido'  => 'Rueda',
                'segundo_apellido' => 'Martinez',
                'fecha_nacimiento' => '1965-12-12',
                'sexo'             => 'M',
                'telefono'         => '95526617',
                'email'            => 'vicente1@gmail.com',
            ],
            [
                'id'               => 2,
                'dni'              => '0601198000245',
                'primer_nombre'    => 'Moises',
                'segundo_nombre'   => null,
                'primer_apellido'  => 'Aguirre',
                'segundo_apellido' => 'Aguirre',
                'fecha_nacimiento' => '1980-04-15',
                'sexo'             => 'M',
                'telefono'         => '89071785',
                'email'            => 'moises12@gmail.com',
            ],
            [
                'id'               => 3,
                'dni'              => '0601200200245',
                'primer_nombre'    => 'Ury',
                'segundo_nombre'   => 'Roberto',
                'primer_apellido'  => 'Aguirre',
                'segundo_apellido' => 'Ramirez',
                'fecha_nacimiento' => '2001-07-22',
                'sexo'             => 'M',
                'telefono'         => '89071785',
                'email'            => 'ury.aguirre@unah.hn',
            ],
            [
                'id'               => 4,
                'dni'              => '78653412',
                'primer_nombre'    => 'Aslan',
                'segundo_nombre'   => null,
                'primer_apellido'  => 'Benedict',
                'segundo_apellido' => null,
                'fecha_nacimiento' => '2009-06-10',
                'sexo'             => 'M',
                'telefono'         => '98765423',
                'email'            => 'aslan.benedict@gmail.com',
            ],
            [
                'id'               => 5,
                'dni'              => '0601200202418',
                'primer_nombre'    => 'Alma',
                'segundo_nombre'   => 'Nicolle',
                'primer_apellido'  => 'Betanourth',
                'segundo_apellido' => 'Martinez',
                'fecha_nacimiento' => '2002-06-13',
                'sexo'             => 'F',
                'telefono'         => '87552427',
                'email'            => 'betancourthalma92@gmail.com',
            ],
            [
                'id'               => 6,
                'dni'              => '0601200303381',
                'primer_nombre'    => 'Mario',
                'segundo_nombre'   => 'Fernando',
                'primer_apellido'  => 'Carbajal',
                'segundo_apellido' => 'Galo',
                'fecha_nacimiento' => '2003-09-02',
                'sexo'             => 'M',
                'telefono'         => '97639800',
                'email'            => 'fernandogalo492@gmail.com',
            ],
            [
                'id'               => 7,
                'dni'              => '0601200401234',
                'primer_nombre'    => 'Obed',
                'segundo_nombre'   => null,
                'primer_apellido'  => 'Contraras',
                'segundo_apellido' => null,
                'fecha_nacimiento' => '2004-04-02',
                'sexo'             => 'M',
                'telefono'         => '87654321',
                'email'            => 'obed.contraras@gmail.com',
            ],
            [
                'id'               => 8,
                'dni'              => '12345677',
                'primer_nombre'    => 'Johana',
                'segundo_nombre'   => null,
                'primer_apellido'  => 'Fernandez',
                'segundo_apellido' => null,
                'fecha_nacimiento' => '2008-12-12',
                'sexo'             => 'F',
                'telefono'         => '12654321',
                'email'            => 'johana.fernandez@gmail.com',
            ],
            [
                'id'               => 9,
                'dni'              => '0601197905678',
                'primer_nombre'    => 'Manuela',
                'segundo_nombre'   => null,
                'primer_apellido'  => 'Fernandez',
                'segundo_apellido' => null,
                'fecha_nacimiento' => '1979-02-12',
                'sexo'             => 'F',
                'telefono'         => '87654322',
                'email'            => 'manuela.fernandez@gmail.com',
            ],
            [
                'id'               => 10,
                'dni'              => '12345678',
                'primer_nombre'    => 'Juan',
                'segundo_nombre'   => null,
                'primer_apellido'  => 'Fernando',
                'segundo_apellido' => null,
                'fecha_nacimiento' => '2006-03-13',
                'sexo'             => 'M',
                'telefono'         => '12345678',
                'email'            => 'juan.fernando@gmail.com',
            ],
            [
                'id'               => 11,
                'dni'              => '87654321',
                'primer_nombre'    => 'Julio',
                'segundo_nombre'   => 'Profe',
                'primer_apellido'  => 'Gomez',
                'segundo_apellido' => null,
                'fecha_nacimiento' => '2001-11-14',
                'sexo'             => 'M',
                'telefono'         => '78560987',
                'email'            => 'julio.gomez@gmail.com',
            ],
            [
                'id'               => 12,
                'dni'              => '0601200402345',
                'primer_nombre'    => 'Martio',
                'segundo_nombre'   => null,
                'primer_apellido'  => 'Joselo',
                'segundo_apellido' => null,
                'fecha_nacimiento' => '2004-04-01',
                'sexo'             => 'M',
                'telefono'         => '87654323',
                'email'            => 'martio.joselo@gmail.com',
            ],
            [
                'id'               => 13,
                'dni'              => '12345698',
                'primer_nombre'    => 'Maria',
                'segundo_nombre'   => null,
                'primer_apellido'  => 'Juana',
                'segundo_apellido' => null,
                'fecha_nacimiento' => '1978-03-12',
                'sexo'             => 'F',
                'telefono'         => '78564378',
                'email'            => 'maria.juana@gmail.com',
            ],
            [
                'id'               => 14,
                'dni'              => '0601200200246',
                'primer_nombre'    => 'Eimy',
                'segundo_nombre'   => 'Mabely',
                'primer_apellido'  => 'Lopez',
                'segundo_apellido' => null,
                'fecha_nacimiento' => '2001-02-11',
                'sexo'             => 'F',
                'telefono'         => '89071786',
                'email'            => 'eimy.lopez@gmail.com',
            ],
            [
                'id'               => 15,
                'dni'              => '0601200200289',
                'primer_nombre'    => 'Martin',
                'segundo_nombre'   => 'Daniel',
                'primer_apellido'  => 'Lopez',
                'segundo_apellido' => 'Ochoa',
                'fecha_nacimiento' => '1999-07-04',
                'sexo'             => 'M',
                'telefono'         => '89674598',
                'email'            => 'martin.lopez@gmail.com',
            ],
            [
                'id'               => 16,
                'dni'              => '0601200403456',
                'primer_nombre'    => 'Martina',
                'segundo_nombre'   => null,
                'primer_apellido'  => 'Lopez',
                'segundo_apellido' => null,
                'fecha_nacimiento' => '2004-04-01',
                'sexo'             => 'F',
                'telefono'         => '87654324',
                'email'            => 'martina.lopez@gmail.com',
            ],
            [
                'id'               => 17,
                'dni'              => '0501200209024',
                'primer_nombre'    => 'Keili',
                'segundo_nombre'   => 'Jazmin',
                'primer_apellido'  => 'Aguilar',
                'segundo_apellido' => 'Garcia',
                'fecha_nacimiento' => '2002-06-27',
                'sexo'             => 'F',
                'telefono'         => '96390056',
                'email'            => 'keili.aguilar@gmail.com',
            ],
            [
                'id'               => 18,
                'dni'              => '0601200404567',
                'primer_nombre'    => 'David',
                'segundo_nombre'   => null,
                'primer_apellido'  => 'Martinez',
                'segundo_apellido' => null,
                'fecha_nacimiento' => '2004-04-02',
                'sexo'             => 'M',
                'telefono'         => '87654325',
                'email'            => 'david.martinez@gmail.com',
            ],
            [
                'id'               => 19,
                'dni'              => '0601199609876',
                'primer_nombre'    => 'Angel',
                'segundo_nombre'   => 'Fernando',
                'primer_apellido'  => 'Perez',
                'segundo_apellido' => 'Maradiaga',
                'fecha_nacimiento' => '1996-05-30',
                'sexo'             => 'M',
                'telefono'         => '98362438',
                'email'            => 'angel.perez@gmail.com',
            ],
            [
                'id'               => 20,
                'dni'              => '12345679',
                'primer_nombre'    => 'Juan',
                'segundo_nombre'   => null,
                'primer_apellido'  => 'Martinez',
                'segundo_apellido' => null,
                'fecha_nacimiento' => '2001-09-12',
                'sexo'             => 'M',
                'telefono'         => '12345678',
                'email'            => 'juan.martinez@gmail.com',
            ],
            [
                'id'               => 21,
                'dni'              => '0601200101356',
                'primer_nombre'    => 'Jimy',
                'segundo_nombre'   => 'Isasias',
                'primer_apellido'  => 'Mendez',
                'segundo_apellido' => 'Espinoza',
                'fecha_nacimiento' => '2000-05-22',
                'sexo'             => 'M',
                'telefono'         => '97400793',
                'email'            => 'jimy.mendez@gmail.com',
            ],
            [
                'id'               => 22,
                'dni'              => '0601200405678',
                'primer_nombre'    => 'Antonio',
                'segundo_nombre'   => null,
                'primer_apellido'  => 'Pinto',
                'segundo_apellido' => null,
                'fecha_nacimiento' => '2004-04-07',
                'sexo'             => 'M',
                'telefono'         => '87654326',
                'email'            => 'antonio.pinto@gmail.com',
            ],
            [
                'id'               => 23,
                'dni'              => '0707198000246',
                'primer_nombre'    => 'Miriam',
                'segundo_nombre'   => 'Janeth',
                'primer_apellido'  => 'Ramirez',
                'segundo_apellido' => null,
                'fecha_nacimiento' => '1980-09-15',
                'sexo'             => 'F',
                'telefono'         => '89891265',
                'email'            => 'miriam.ramirez@gmail.com',
            ],
            [
                'id'               => 24,
                'dni'              => '0601200406789',
                'primer_nombre'    => 'Mariana',
                'segundo_nombre'   => null,
                'primer_apellido'  => 'Rodrigue',
                'segundo_apellido' => null,
                'fecha_nacimiento' => '2004-04-01',
                'sexo'             => 'F',
                'telefono'         => '87654327',
                'email'            => 'mariana.rodrigue@gmail.com',
            ],
            [
                'id'               => 25,
                'dni'              => '0601198900123',
                'primer_nombre'    => 'Josefina',
                'segundo_nombre'   => null,
                'primer_apellido'  => 'Rodriguez',
                'segundo_apellido' => null,
                'fecha_nacimiento' => '1989-08-13',
                'sexo'             => 'F',
                'telefono'         => '87654328',
                'email'            => 'josefina.rodriguez@gmail.com',
            ],
            [
                'id'               => 26,
                'dni'              => '0801197302222',
                'primer_nombre'    => 'Maria',
                'segundo_nombre'   => 'Del',
                'primer_apellido'  => 'Carmen',
                'segundo_apellido' => 'Valladares',
                'fecha_nacimiento' => '1973-04-05',
                'sexo'             => 'F',
                'telefono'         => '89768945',
                'email'            => 'maria.carmen@gmail.com',
            ],
        ];

        $now = now();
        DB::table('personas')->insert(
            array_map(fn($p) => array_merge($p, ['created_at' => $now, 'updated_at' => $now]), $personas)
        );
    }
}
